-- +goose Up
CREATE SCHEMA IF NOT EXISTS auth;
CREATE SCHEMA IF NOT EXISTS master;
CREATE SCHEMA IF NOT EXISTS game;
CREATE SCHEMA IF NOT EXISTS leaderboard;
CREATE SCHEMA IF NOT EXISTS notifications;
CREATE SCHEMA IF NOT EXISTS analytics;

-- +goose Down
DROP SCHEMA IF EXISTS analytics CASCADE;
DROP SCHEMA IF EXISTS notifications CASCADE;
DROP SCHEMA IF EXISTS leaderboard CASCADE;
DROP SCHEMA IF EXISTS game CASCADE;
DROP SCHEMA IF EXISTS master CASCADE;
DROP SCHEMA IF EXISTS auth CASCADE;
